### PR TITLE
Added Alternative Solution to Smiling ASCII - Forensics

### PR DESCRIPTION
**Pull request by vivian-dai**
not sure what your policies are on alternate solutions

### CODE REVIEW

**Comment by vivian-dai** [comment]
The commit was made by me, I just made a typo in the email

**Comment by rishitsaiya** [comment]
How about we put `another_name(something like alternate soln).md` so that it doesn't interfere with the primary `README.md` being shown [here](https://github.com/rishitsaiya/CTFlearn-Writeups/tree/master/Forensics/Smiling%20ASCII)

**Comment by vivian-dai** [comment]
I've put the alternative solution in [another file](https://github.com/rishitsaiya/CTFlearn-Writeups/pull/91/commits/caf3b45b1f52214b9eeb50de787b690e05c0caec#diff-fa90f8316520e3425d25d0690ff6923d2b87aff77ac615a0fbe0ac5f9842f083)

**Review by rishitsaiya — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
