### PR TITLE
Updated Ambush Mission - Miscellaneous

### PR DESCRIPTION
**Pull request by vivian-dai**
Wrapping the flag in the flag format for the challenge

### CODE REVIEW

**Comment by vivian-dai** [comment]
Also added [Image Magic](https://ctflearn.com/challenge/89)

**Comment by rishitsaiya** [comment]
Add the name as `Alternative Soln or something.md` to the writeup.

**Comment by vivian-dai** [comment]
Oh Image Magic got moved to programming. I will change that

**Comment by rishitsaiya** [comment]
Sorry for the delay! Merged here!

**Pull request merged**
